# Generated by Django 3.0 on 2019-12-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photographer',
        ),
    ]
