# Generated by Django 3.0 on 2019-12-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20191216_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image',
            new_name='photo',
        ),
    ]
