# Generated by Django 3.0 on 2019-12-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20191216_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photo',
            new_name='image',
        ),
    ]
